---
# tasks file for user_security
- name: Install symas.com repo for openldap-servers
  when: dist == 'el8' and ldap_server != ''
  get_url:
    url: https://repo.symas.com/configs/SOFL/rhel8/sofl.repo
    dest: /etc/yum.repos.d/sofl.repo

- name: Vault Role
  when: vault_version != ''
  include_role:
    name: vault

- name: Install db packages
  include_tasks: common/tasks/install_db_packages.yml

- name: Install Samba Active Directory server
  when: samba_ad != '' and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux')
  shell:
    cmd: /bin/bash /vagrant/tools/install_samba_ad.sh
    creates: /opt/samba/sbin/samba

- name: Setup Samba Active Directory server
  when: samba_ad != '' and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux')
  shell:
    cmd: /bin/bash /vagrant/tools/setup_samba_ad.sh
    creates: /root/samba.configured

- name: Setup LDAP server
  when: ldap_server != ''
  command:
    cmd: /bin/bash /vagrant/tools/setup_ldap_server.sh "{{db_user}}" "{{db_password}}" "ssl"
    creates: /root/ldaprootpasswd.ldif

- name: Setup LDAP on client
  when: ldap_server_ip != ''
  command:
    cmd: /bin/bash /vagrant/tools/setup_ldap_client.sh "{{ldap_server_ip}}"
    creates: /root/ldap-client.configured

- name: Setup Kerberos server
  when: kerberos_server != ''
  command:
    cmd: /bin/bash /vagrant/tools/setup_kerberos_server.sh "{{db_user}}" "{{db_password}}"
    creates: /root/kerberos.configured

- name: Setup Kerberos client
  when: kerberos_client != ''
  command:
    cmd: /bin/bash /vagrant/tools/setup_kerberos_client.sh "{{db_user}}" "{{db_password}}" "{{ 'yes' if samba_kerberos != '' else 'no' }}"
    creates: /root/kerberos-client.configured


