---
# tasks file for tools_and_monitoring
# PMM
- name: install podman (like docker)
  when: pmm_server_version != ""
  package:
    name: podman
    state: present
- name: Start PMM
  when: pmm_server_version != ""
  shell:
    cmd: "podman create -v /srv --name pmm-data docker.io/percona/pmm-server:{{ pmm_server_version }} /bin/true ; podman run -d -p 80:80 -p 443:443 --volumes-from pmm-data --name pmm-server docker.io/percona/pmm-server:{{ pmm_server_version }} ; podman ps | grep pmm-server && touch /root/pmm-server-created"
    creates: /root/pmm-server-created
- name: Set PMM2 password
  when: pmm_server_version.startswith('2.') and db_password != ''
  command:
    cmd: podman exec -t pmm-server bash -c  'ln -s /srv/grafana /usr/share/grafana/data; grafana-cli --homepath /usr/share/grafana admin reset-admin-password {{db_password}}'

- name: install Percona Toolkit
  when: percona_toolkit_version != ""
  package:
    name: "percona-toolkit-{{ percona_toolkit_version }}.{{dist}}.x86_64"
    state: present


