---
# tasks file for tools_and_monitoring
# PMM
- name: install podman (like docker)
  when: pmm_server_version != ""
  package:
    name: podman
    state: present
- name: install Percona Toolkit
  when: percona_toolkit_version != ""
  package:
    name: "{{item}}"
    state: present
  with_items: "{{ os[dist]['percona_toolkit'].install_packages }}"

- name: PMM Setup tasks
  when: install_only == ''
  include_tasks: setup.yaml
