---
# tasks file for tools_and_monitoring
# PMM
- name: install podman (like docker)
  when: pmm_server_version != ""
  package:
    name: podman
    state: present
- name: install Percona Toolkit
  when: percona_toolkit_version != ""
  package:
    name: "percona-toolkit-{{ percona_toolkit_version }}.{{dist}}.x86_64"
    state: present

- name: PMM Setup tasks
  when: install_only == ''
  include_tasks: setup.yaml
