---
# vars file for postgresql
pkg:
  el7:
    install_packages:
      - "percona-postgresql{{ percona_postgresql_major_ver }}-libs-{{ percona_postgresql_version }}.{{ dist }}.x86_64"
      - "percona-postgresql{{ percona_postgresql_major_ver }}-{{ percona_postgresql_version }}.{{ dist }}.x86_64"
      - "percona-postgresql{{ percona_postgresql_major_ver }}-server-{{ percona_postgresql_version }}.{{ dist }}.x86_64"
      - "percona-postgresql{{ percona_postgresql_major_ver }}-contrib-{{ percona_postgresql_version }}.{{ dist }}.x86_64"
  el8:
    install_packages:
      - "percona-postgresql{{ percona_postgresql_major_ver }}-libs-{{ percona_postgresql_version }}.{{ dist }}.x86_64"
      - "percona-postgresql-common-{{percona_postgresql_version2}}.{{dist}}"
      - "https://repo.percona.com/ppg-{{ percona_postgresql_major_ver }}/yum/release/8/RPMS/x86_64/percona-postgresql{{ percona_postgresql_major_ver }}-{{ percona_postgresql_version }}.{{dist}}.x86_64.rpm"
      - "https://repo.percona.com/ppg-{{ percona_postgresql_major_ver }}/yum/release/8/RPMS/x86_64/percona-postgresql{{ percona_postgresql_major_ver }}-server-{{ percona_postgresql_version }}.{{dist}}.x86_64.rpm"
      - "https://repo.percona.com/ppg-{{ percona_postgresql_major_ver }}/yum/release/8/RPMS/x86_64/percona-postgresql{{ percona_postgresql_major_ver }}-contrib-{{ percona_postgresql_version }}.{{dist}}.x86_64.rpm"
  focal:
    systemd: "postgresql@{{percona_postgresql_major_ver}}-main"
    install_packages:
      - "libpq5=2:{{ percona_postgresql_version }}.{{ dist }}"
      - "percona-postgresql-client-common={{percona_postgresql_version2}}.{{ dist }}"
      - "percona-postgresql-common={{percona_postgresql_version2}}.focal"
      - "percona-postgresql-client-{{ percona_postgresql_major_ver }}=2:{{ percona_postgresql_version }}.{{ dist }}"
      - "percona-postgresql-{{ percona_postgresql_major_ver }}=2:{{ percona_postgresql_version }}.{{ dist }}"

maj: "{{'9.5' if postgresql_version.startswith('9.5') else '9.6' if postgresql_version.startswith('9.6') else postgresql_version|regex_replace('^([0-9]+)[-.].*$','\\1') if postgresql_version != '' else percona_postgresql_version|regex_replace('^([0-9]+)[-.].*$','\\1')   }}"
pg_conf_dir: "{{ '/var/lib/pgsql/'+maj+'/data' if ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux' else '/etc/postgresql/'+maj+'/main'}}"
pg_data_dir: "{{ '/var/lib/pgsql/'+maj+'/data' if ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux' else '/var/lib/postgresql/'+maj+'/main'}}"
pg_systemd_svc: "{{ pkg[dist].systemd if ('systemd' in pkg[dist]) and percona_postgresql_version !='' else os[dist][soft].systemd_service if soft else db_systemd_service }}"
