---
# vars file for postgresql
pkg:
  el7:
    install_packages:
      - "percona-postgresql{{ percona_postgresql_major_ver }}-libs-{{ percona_postgresql_version }}.{{ dist }}.x86_64"
      - "percona-postgresql{{ percona_postgresql_major_ver }}-{{ percona_postgresql_version }}.{{ dist }}.x86_64"
      - "percona-postgresql{{ percona_postgresql_major_ver }}-server-{{ percona_postgresql_version }}.{{ dist }}.x86_64"
      - "percona-postgresql{{ percona_postgresql_major_ver }}-contrib-{{ percona_postgresql_version }}.{{ dist }}.x86_64"
  el8:
    install_packages:
      - "percona-postgresql{{ percona_postgresql_major_ver }}-libs-{{ percona_postgresql_version }}.{{ dist }}.x86_64"
      - "percona-postgresql-common-{{percona_postgresql_version2}}.{{dist}}"
      - "https://repo.percona.com/ppg-{{ percona_postgresql_major_ver }}/yum/release/8/RPMS/x86_64/percona-postgresql{{ percona_postgresql_major_ver }}-{{ percona_postgresql_version }}.{{dist}}.x86_64.rpm"
      - "https://repo.percona.com/ppg-{{ percona_postgresql_major_ver }}/yum/release/8/RPMS/x86_64/percona-postgresql{{ percona_postgresql_major_ver }}-server-{{ percona_postgresql_version }}.{{dist}}.x86_64.rpm"
      - "https://repo.percona.com/ppg-{{ percona_postgresql_major_ver }}/yum/release/8/RPMS/x86_64/percona-postgresql{{ percona_postgresql_major_ver }}-contrib-{{ percona_postgresql_version }}.{{dist}}.x86_64.rpm"
  focal:
    systemd: "postgresql@{{percona_postgresql_major_ver}}-main"
    install_packages:
      - "libpq5=2:{{ percona_postgresql_version }}.{{ dist }}"
      - "percona-postgresql-client-common={{percona_postgresql_version2}}.{{ dist }}"
      - "percona-postgresql-common={{percona_postgresql_version2}}.focal"
      - "percona-postgresql-client-{{ percona_postgresql_major_ver }}=2:{{ percona_postgresql_version }}.{{ dist }}"
      - "percona-postgresql-{{ percona_postgresql_major_ver }}=2:{{ percona_postgresql_version }}.{{ dist }}"

