- name: Reduce overhead, disable traefik
  when: k3s_url == ""
  replace:
    path: /etc/systemd/system/k3s.service
    regexp: '/usr/local/bin/k3s server$'
    replace: "/usr/local/bin/k3s server --no-deploy traefik --flannel-backend={{k3s_flannel_backend if k3s_flannel_backend != '' else 'host-gw'}}"
- name: Adapt k3s.service for non-master node
  when: k3s_token != "" and k3s_url != ""
  block:
    - name: Fix env file
      replace:
        path: /etc/systemd/system/k3s-agent.service
        regexp: '/etc/systemd/system/k3s.service.env'
        replace: '/etc/systemd/system/k3s-agent.service.env'
    - name: Fix service command
      replace:
        path: /etc/systemd/system/k3s-agent.service
        regexp: '/usr/local/bin/k3s server'
        replace: '/usr/local/bin/k3s agent'

- name: Start k3s
  shell:
    warn: false
    cmd: "echo {{ '' if k3s_url == '' else 'K3S_URL='+k3s_url }} > /etc/systemd/system/k3s{{ '' if k3s_url == '' else '-agent' }}.service.env;echo {{ '' if k3s_token == '' else 'K3S_TOKEN='+k3s_token }} >> /etc/systemd/system/k3s{{ '' if k3s_url == '' else '-agent' }}.service.env;systemctl daemon-reload; systemctl start k3s{{ '' if k3s_url == '' else '-agent' }}"
    creates: /etc/systemd/system/k3s{{ '' if k3s_url == '' else '-agent' }}.service.env

- name: Setup k3s .kube/config
  when: k3s_url == ''
  shell:
    warn: false
    cmd: mkdir /root/.kube;chmod 0700 /root/.kube;cp /etc/rancher/k3s/k3s.yaml /root/.kube/config
    creates: /root/.kube/config
