---
# vars file for mongodb
pkg:
  el7:
    install_packages:
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-tools-{{ psmdb_version }}.{{ dist }}.x86_64"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-shell-{{ psmdb_version }}.{{ dist }}.x86_64"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-server-{{ psmdb_version }}.{{ dist }}.x86_64"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-mongos-{{ psmdb_version }}.{{ dist }}.x86_64"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-{{ psmdb_version }}.{{ dist }}.x86_64"
  el8:
    install_packages:
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-tools-{{ psmdb_version }}.{{ dist }}.x86_64"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-shell-{{ psmdb_version }}.{{ dist }}.x86_64"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-server-{{ psmdb_version }}.{{ dist }}.x86_64"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-mongos-{{ psmdb_version }}.{{ dist }}.x86_64"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-{{ psmdb_version }}.{{ dist }}.x86_64"
  focal:
    install_packages:
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-tools={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-shell={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-server={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}-mongos={{ psmdb_version }}.{{ dist }}"
      - "{{ psmdb_name }}{{ psmdb_major_ver }}={{ psmdb_version }}.{{ dist }}"
